INSERT INTO category (is_allowed, name)
VALUES
    (true, 'Sunglasses'),
    (true, 'Fashion accessory'),
    (true, 'Watch'),
    (true, 'Handbag'),
    (true, 'Wallet'),
    (true, 'Scarf'),
    (true, 'Belt'),
    (true, 'Hat'),
    (true, 'Necklace'),
    (true, 'Earring'),
    (true, 'Bracelet'),
    (true, 'Ring'),
    (true, 'Glove'),
    (true, 'Tie'),
    (true, 'Bowtie'),
    (true, 'Headband'),
    (true, 'Hair clip'),
    (true, 'Brooch'),
    (true, 'Pet'),
    (true, 'Pocket square'),
    (true, 'Sock'),
    (true, 'Shoe clip'),
    (true, 'Insole'),
    (true, 'Lace'),
    (true, 'Handkerchief'),
    (true, 'Computer'),
    (true, 'Shawl'),
    (true, 'Evening bag'),
    (true, 'Belt buckle'),
    (true, 'Wallet chain'),
    (true, 'Anklet'),
    (true, 'Body chain'),
    (true, 'Mobile phone'),
    (true, 'Luxury watch'),
    (true, 'Smartphone case'),
    (true, 'Umbrella'),
    (true, 'Jacket'),
    (true, 'Shirt'),
    (true, 'Pants'),
    (true, 'Skirt'),
    (true, 'Dress'),
    (true, 'T-shirt'),
    (true, 'Blouse'),
    (true, 'Shorts'),
    (true, 'Suit'),
    (true, 'Sweater'),
    (true, 'Hoodie'),
    (true, 'Cardigan'),
    (true, 'Coat'),
    (true, 'Pajamas'),
    (true, 'Socks'),
    (true, 'Gloves'),
    (true, 'Laptop'),
    (true, 'Sneaker'),
    (true, 'Boot'),
    (true, 'Sandal'),
    (true, 'Heel'),
    (true, 'Loafer'),
    (true, 'Flats'),
    (true, 'Flip-flop'),
    (true, 'Oxford'),
    (true, 'Running shoes'),
    (true, 'Lipstick'),
    (true, 'Foundation'),
    (true, 'Mascara'),
    (true, 'Eyeshadow'),
    (true, 'Nail polish'),
    (true, 'Blush'),
    (true, 'Perfume'),
    (true, 'Hair dye'),
    (true, 'Stuffed animal'),
    (true, 'Doll'),
    (true, 'Toy car'),
    (true, 'Building blocks'),
    (true, 'Puzzle'),
    (true, 'Action figure'),
    (true, 'Educational toy'),
    (true, 'Toy'),
    (true, 'Headphones'),
    (true, 'Laptop bag'),
    (true, 'Portable charger'),
    (true, 'Earbuds'),
    (true, 'Computer accessory'),
    (true, 'Smartwatch'),
    (true, 'Phone'),
    (true, 'VR'),
    (true, 'Tablet case'),
    (true, 'Dog supply'),
    (true, 'Cat supply'),
    (true, 'Pet collar'),
    (true, 'Pet accessory'),
    (true, 'Pet bed'),
    (true, 'Pet food bowl'),
    (true, 'Pet toy'),
    (true, 'Pet grooming products'),
    (true, 'Pet clothing'),
    (true, 'Glasses'),
    (false, 'Snack'),
    (false, 'Candy'),
    (false, 'Chocolate'),
    (false, 'Canned food'),
    (false, 'Fruit'),
    (false, 'Dairy products'),
    (false, 'Meat'),
    (false, 'Frozen foods'),
    (false, 'Cereals'),
    (false, 'Juice'),
    (false, 'Soda'),
    (false, 'Alcohol'),
    (false, 'Baseball bat'),
    (false, 'Football'),
    (false, 'Tennis racket'),
    (false, 'Hockey stick'),
    (false, 'Golf club'),
    (false, 'Basketball'),
    (false, 'Soccer ball'),
    (false, 'Ski equipment'),
    (false, 'Exercise bike'),
    (false, 'Dumbbells'),
    (false, 'Cigarette'),
    (false, 'Cigar'),
    (false, 'Smoking pipe'),
    (false, 'Hookah'),
    (false, 'E-cigarette'),
    (false, 'Cigarette lighter'),
    (false, 'Chewing tobacco'),
    (false, 'Bleach'),
    (false, 'Detergent'),
    (false, 'Dish soap'),
    (false, 'Toilet cleaner'),
    (false, 'Fabric softener'),
    (false, 'Air freshener'),
    (false, 'Floor cleaner'),
    (false, 'Glass cleaner'),
    (false, 'Gun'),
    (false, 'Knife'),
    (false, 'Sword'),
    (false, 'Rifle'),
    (false, 'Crossbow'),
    (false, 'Ammunition'),
    (false, 'Bulletproof vest'),
    (false, 'Military uniform'),
    (false, 'Car'),
    (false, 'Motorcycle'),
    (false, 'Bicycle'),
    (false, 'Truck'),
    (false, 'Spare tire'),
    (false, 'Car battery'),
    (false, 'Car engine'),
    (false, 'Vehicle mirrors'),
    (false, 'Fur coat'),
    (false, 'Fur hat'),
    (false, 'Fur gloves'),
    (false, 'Fur collar'),
    (false, 'Fur shawl'),
    (false, 'Fur boots'),
    (false, 'Fur clothing'),
    (false, 'Fur accessory'),
    (false, 'Fur bag'),
    (false, 'Gun accessory'),
    (false, 'Machine gun'),
    (false, 'Shotgun'),
    (false, 'Gun barrel'),
    (false, 'Tobacco'),
    (false, 'Tobacco products'),
    (false, 'Bullet');

