INSERT INTO category (is_allowed, name)
VALUES
    (true, 'Sunglasses'),
    (true, 'Fashion Accessory'),
    (true, 'Watch'),
    (true, 'Handbag'),
    (true, 'Wallet'),
    (true, 'Scarf'),
    (true, 'Belt'),
    (true, 'Hat'),
    (true, 'Necklace'),
    (true, 'Earring'),
    (true, 'Bracelet'),
    (true, 'Ring'),
    (true, 'Glove'),
    (true, 'Tie'),
    (true, 'Bowtie'),
    (true, 'Headband'),
    (true, 'Hair Clip'),
    (true, 'Brooch'),
    (true, 'Pet'),
    (true, 'Pocket Square'),
    (true, 'Sock'),
    (true, 'Shoe Clip'),
    (true, 'Insole'),
    (true, 'Lace'),
    (true, 'Handkerchief'),
    (true, 'Computer'),
    (true, 'Shawl'),
    (true, 'Evening Bag'),
    (true, 'Belt Buckle'),
    (true, 'Wallet Chain'),
    (true, 'Anklet'),
    (true, 'Body Chain'),
    (true, 'Mobile Phone'),
    (true, 'Luxury Watch'),
    (true, 'Smartphone Case'),
    (true, 'Umbrella'),
    (true, 'Jacket'),
    (true, 'Shirt'),
    (true, 'Pants'),
    (true, 'Skirt'),
    (true, 'Dress'),
    (true, 'T-shirt'),
    (true, 'Blouse'),
    (true, 'Shorts'),
    (true, 'Suit'),
    (true, 'Sweater'),
    (true, 'Hoodie'),
    (true, 'Cardigan'),
    (true, 'Coat'),
    (true, 'Pajamas'),
    (true, 'Socks'),
    (true, 'Gloves'),
    (true, 'Laptop'),
    (true, 'Sneaker'),
    (true, 'Boot'),
    (true, 'Sandal'),
    (true, 'Heel'),
    (true, 'Loafer'),
    (true, 'Flats'),
    (true, 'Flip-flop'),
    (true, 'Oxford'),
    (true, 'Running Shoes'),
    (true, 'Lipstick'),
    (true, 'Foundation'),
    (true, 'Mascara'),
    (true, 'Eyeshadow'),
    (true, 'Nail Polish'),
    (true, 'Blush'),
    (true, 'Perfume'),
    (true, 'Hair Dye'),
    (true, 'Stuffed Animal'),
    (true, 'Doll'),
    (true, 'Toy Car'),
    (true, 'Building Blocks'),
    (true, 'Puzzle'),
    (true, 'Action Figure'),
    (true, 'Educational Toy'),
    (true, 'Toy'),
    (true, 'Headphones'),
    (true, 'Laptop Bag'),
    (true, 'Portable Charger'),
    (true, 'Earbuds'),
    (true, 'Computer Accessory'),
    (true, 'Smartwatch'),
    (true, 'Phone'),
    (true, 'VR'),
    (true, 'Tablet Case'),
    (true, 'Dog supply'),
    (true, 'Cat supply'),
    (true, 'Pet Collar'),
    (true, 'Pet Accessory'),
    (true, 'Pet Bed'),
    (true, 'Pet Food Bowl'),
    (true, 'Pet Toy'),
    (true, 'Pet Grooming Products'),
    (true, 'Pet Clothing');
